## GENERATED from vocabulary.json by dev/gen_vocabulary.gd -- DO NOT EDIT.
## Regenerate after any vocabulary.json change:
##   godot --headless --path . --script res://addons/reactive_ui/dev/gen_vocabulary.gd
##
## Embedded as a script const so the compiler needs NO runtime file read: during the
## editor's first filesystem scan, FileAccess reads return empty (the GUITKX2507 cold-open
## wall) while script loading is reliable -- if guitkx.gd loads, this Dictionary exists.
## tests/guitkx_test.gd fails when this file drifts from vocabulary.json.
const DATA: Dictionary = {
	"__comment": "SINGLE SOURCE OF TRUTH for the .guitkx language vocabulary (SYNTAX_PARITY_EXECUTION_PLAN T0.3). Consumed by guitkx.gd (HOST_TAGS / HOOK_NAMES) and by the LSP (ide-extensions/lsp-server/src/vocabulary.json is a byte-identical copy shipped with the extension; a test enforces the sync). v_factories mirrors the public static funcs of addons/reactive_ui/core/v.gd (a reflection tripwire test enforces it). Edit HERE, then copy to the lsp-server and rerun both test suites. NAMING (0.9.0, plans/NAMING_LOYALTY_PROPOSAL.md): host tags ARE the official Godot class names and factories match tags verbatim; host_tags is the CURATED set (IDE metadata) — the compiler additionally accepts ANY instantiable ClassDB Node class as a tag (open vocabulary, emitted as V.h). DIVERGENCE (0.10.2, plans/archive/CLASSNAME_CLEANUP_PLAN.md): GUITKX0103 is registered here but retired from emission on the Godot leg — imports made filename identity moot, so `component X differs from file name Y` no longer fires. The number is reserved and never reused (old sidecars still render it; other family legs may still emit it).",
	"directives": [
		"class_name",
		"if",
		"elif",
		"else",
		"for",
		"while",
		"match",
		"case",
		"default"
	],
	"hooks": [
		"useState",
		"useReducer",
		"useRef",
		"useMemo",
		"useCallback",
		"useImperativeHandle",
		"useEffect",
		"useLayoutEffect",
		"createContext",
		"useContext",
		"provideContext",
		"useDeferredValue",
		"useTransition",
		"useStableCallback",
		"useStableFunc",
		"useStableAction",
		"useSafeArea",
		"useSignal",
		"useSignalKey",
		"useTween",
		"useTweenValue",
		"useAnimate",
		"useSfx"
	],
	"host_tags": {
		"AspectRatioContainer": "AspectRatioContainer",
		"AudioStreamPlayer": "AudioStreamPlayer",
		"BoxContainer": "BoxContainer",
		"Button": "Button",
		"CenterContainer": "CenterContainer",
		"CheckBox": "CheckBox",
		"CheckButton": "CheckButton",
		"CodeEdit": "CodeEdit",
		"ColorPicker": "ColorPicker",
		"ColorPickerButton": "ColorPickerButton",
		"ColorRect": "ColorRect",
		"Control": "Control",
		"FlowContainer": "FlowContainer",
		"FoldableContainer": "FoldableContainer",
		"Fragment": "fragment",
		"GridContainer": "GridContainer",
		"HBoxContainer": "HBoxContainer",
		"HFlowContainer": "HFlowContainer",
		"HScrollBar": "HScrollBar",
		"HSeparator": "HSeparator",
		"HSlider": "HSlider",
		"HSplitContainer": "HSplitContainer",
		"ItemList": "ItemList",
		"Label": "Label",
		"LineEdit": "LineEdit",
		"LinkButton": "LinkButton",
		"MarginContainer": "MarginContainer",
		"MenuBar": "MenuBar",
		"MenuButton": "MenuButton",
		"NinePatchRect": "NinePatchRect",
		"OptionButton": "OptionButton",
		"Panel": "Panel",
		"PanelContainer": "PanelContainer",
		"ProgressBar": "ProgressBar",
		"ReferenceRect": "ReferenceRect",
		"RichTextLabel": "RichTextLabel",
		"ScrollContainer": "ScrollContainer",
		"SpinBox": "SpinBox",
		"SplitContainer": "SplitContainer",
		"SubViewportContainer": "SubViewportContainer",
		"TabBar": "TabBar",
		"TabContainer": "TabContainer",
		"TextEdit": "TextEdit",
		"TextureButton": "TextureButton",
		"TextureProgressBar": "TextureProgressBar",
		"TextureRect": "TextureRect",
		"Tree": "Tree",
		"VBoxContainer": "VBoxContainer",
		"VFlowContainer": "VFlowContainer",
		"VScrollBar": "VScrollBar",
		"VSeparator": "VSeparator",
		"VSlider": "VSlider",
		"VSplitContainer": "VSplitContainer",
		"VideoStreamPlayer": "VideoStreamPlayer",
		"VirtualJoystick": "VirtualJoystick"
	},
	"live": [
		"GUITKX0013",
		"GUITKX0014",
		"GUITKX0015",
		"GUITKX0016",
		"GUITKX2101",
		"GUITKX0104",
		"GUITKX0105",
		"GUITKX0109",
		"GUITKX0108",
		"GUITKX0107",
		"GUITKX0150",
		"GUITKX0300",
		"GUITKX0301",
		"GUITKX0302",
		"GUITKX0303",
		"GUITKX0304",
		"GUITKX0305",
		"GUITKX2506",
		"GUITKX2508",
		"GUITKX2100",
		"GUITKX2103",
		"GUITKX2104",
		"GUITKX2105",
		"GUITKX2203",
		"GUITKX0106"
	],
	"renamed_tags": {
		"Center": "CenterContainer",
		"Grid": "GridContainer",
		"HBox": "HBoxContainer",
		"Margin": "MarginContainer",
		"RichText": "RichTextLabel",
		"Scroll": "ScrollContainer",
		"Tabs": "TabContainer",
		"VBox": "VBoxContainer"
	},
	"severities": {
		"GUITKX0013": "error",
		"GUITKX0014": "error",
		"GUITKX0015": "error",
		"GUITKX0016": "error",
		"GUITKX0018": "warning",
		"GUITKX0019": "warning",
		"GUITKX0026": "error",
		"GUITKX0103": "warning",
		"GUITKX0104": "error",
		"GUITKX0105": "error",
		"GUITKX0106": "warning",
		"GUITKX0107": "hint",
		"GUITKX0108": "error",
		"GUITKX0109": "error",
		"GUITKX0111": "warning",
		"GUITKX0120": "error",
		"GUITKX0121": "error",
		"GUITKX0150": "warning",
		"GUITKX0151": "warning",
		"GUITKX0300": "error",
		"GUITKX0301": "error",
		"GUITKX0302": "error",
		"GUITKX0303": "error",
		"GUITKX0304": "error",
		"GUITKX0305": "error",
		"GUITKX2100": "error",
		"GUITKX2101": "error",
		"GUITKX2102": "error",
		"GUITKX2103": "error",
		"GUITKX2104": "error",
		"GUITKX2105": "error",
		"GUITKX2106": "error",
		"GUITKX2107": "error",
		"GUITKX2203": "warning",
		"GUITKX2210": "error",
		"GUITKX2300": "error",
		"GUITKX2301": "error",
		"GUITKX2302": "error",
		"GUITKX2303": "error",
		"GUITKX2304": "warning",
		"GUITKX2305": "error",
		"GUITKX2306": "error",
		"GUITKX2307": "error",
		"GUITKX2308": "error",
		"GUITKX2309": "error",
		"GUITKX2504": "error",
		"GUITKX2505": "error",
		"GUITKX2506": "error",
		"GUITKX2507": "error",
		"GUITKX2508": "error"
	},
	"v_factories": [
		"AspectRatioContainer",
		"AudioStreamPlayer",
		"BoxContainer",
		"Button",
		"CenterContainer",
		"CheckBox",
		"CheckButton",
		"CodeEdit",
		"ColorPicker",
		"ColorPickerButton",
		"ColorRect",
		"Control",
		"FlowContainer",
		"FoldableContainer",
		"GridContainer",
		"HBoxContainer",
		"HFlowContainer",
		"HScrollBar",
		"HSeparator",
		"HSlider",
		"HSplitContainer",
		"ItemList",
		"Label",
		"LineEdit",
		"LinkButton",
		"MarginContainer",
		"MenuBar",
		"MenuButton",
		"NinePatchRect",
		"OptionButton",
		"Panel",
		"PanelContainer",
		"ProgressBar",
		"ReferenceRect",
		"RichTextLabel",
		"ScrollContainer",
		"SpinBox",
		"SplitContainer",
		"SubViewportContainer",
		"TabBar",
		"TabContainer",
		"TextEdit",
		"TextureButton",
		"TextureProgressBar",
		"TextureRect",
		"Tree",
		"VBoxContainer",
		"VFlowContainer",
		"VScrollBar",
		"VSeparator",
		"VSlider",
		"VSplitContainer",
		"VideoStreamPlayer",
		"VirtualJoystick",
		"comp",
		"error_boundary",
		"fc",
		"fragment",
		"h",
		"link",
		"memo",
		"nav_link",
		"navigate",
		"outlet",
		"portal",
		"route",
		"router",
		"routes",
		"suspense",
		"text"
	]
}
