## GENERATED from vocabulary.json by dev/gen_vocabulary.gd -- DO NOT EDIT.
## Regenerate after any vocabulary.json change:
##   godot --headless --path . --script res://addons/reactive_ui/dev/gen_vocabulary.gd
##
## Embedded as a script const so the compiler needs NO runtime file read: during the
## editor's first filesystem scan, FileAccess reads return empty (the GUITKX2507 cold-open
## wall) while script loading is reliable -- if guitkx.gd loads, this Dictionary exists.
## tests/guitkx_test.gd fails when this file drifts from vocabulary.json.
const DATA: Dictionary = {
	"__comment": "SINGLE SOURCE OF TRUTH for the .guitkx language vocabulary (SYNTAX_PARITY_EXECUTION_PLAN T0.3). Consumed by guitkx.gd (HOST_TAGS / HOOK_NAMES) and by the LSP (ide-extensions/lsp-server/src/vocabulary.json is a byte-identical copy shipped with the extension; a test enforces the sync). v_factories mirrors the public static funcs of addons/reactive_ui/core/v.gd (a reflection tripwire test enforces it). Edit HERE, then copy to the lsp-server and rerun both test suites.",
	"directives": [
		"class_name",
		"if",
		"elif",
		"else",
		"for",
		"while",
		"match",
		"case",
		"default"
	],
	"hooks": [
		"useState",
		"useReducer",
		"useRef",
		"useMemo",
		"useCallback",
		"useImperativeHandle",
		"useEffect",
		"useLayoutEffect",
		"createContext",
		"useContext",
		"provideContext",
		"useDeferredValue",
		"useTransition",
		"useStableCallback",
		"useStableFunc",
		"useStableAction",
		"useSafeArea",
		"useSignal",
		"useSignalKey",
		"useTween",
		"useTweenValue",
		"useAnimate",
		"useSfx"
	],
	"host_tags": {
		"Button": "button",
		"Center": "center",
		"CenterContainer": "center",
		"CheckBox": "check_box",
		"CheckButton": "check_button",
		"CodeEdit": "code_edit",
		"ColorRect": "color_rect",
		"Control": "control",
		"Fragment": "fragment",
		"Grid": "grid",
		"GridContainer": "grid",
		"HBox": "hbox",
		"HBoxContainer": "hbox",
		"HSeparator": "h_separator",
		"HSlider": "h_slider",
		"ItemList": "item_list",
		"Label": "label",
		"LineEdit": "line_edit",
		"LinkButton": "link_button",
		"Margin": "margin",
		"MarginContainer": "margin",
		"MenuButton": "menu_button",
		"OptionButton": "option_button",
		"Panel": "panel",
		"PanelContainer": "panel",
		"ProgressBar": "progress_bar",
		"RichText": "rich_text",
		"RichTextLabel": "rich_text",
		"Scroll": "scroll",
		"ScrollContainer": "scroll",
		"SpinBox": "spin_box",
		"TabBar": "tab_bar",
		"TabContainer": "tabs",
		"Tabs": "tabs",
		"TextEdit": "text_edit",
		"TextureButton": "texture_button",
		"TextureRect": "texture_rect",
		"Tree": "tree",
		"VBox": "vbox",
		"VBoxContainer": "vbox",
		"VSeparator": "v_separator",
		"VSlider": "v_slider"
	},
	"live": [
		"GUITKX0013",
		"GUITKX0014",
		"GUITKX0015",
		"GUITKX0016",
		"GUITKX2101",
		"GUITKX0104",
		"GUITKX0105",
		"GUITKX0109",
		"GUITKX0108",
		"GUITKX0107",
		"GUITKX0150",
		"GUITKX0300",
		"GUITKX0301",
		"GUITKX0302",
		"GUITKX0303",
		"GUITKX0304",
		"GUITKX0305",
		"GUITKX2506",
		"GUITKX2508",
		"GUITKX2100",
		"GUITKX2103",
		"GUITKX2104",
		"GUITKX2105",
		"GUITKX2203",
		"GUITKX0106"
	],
	"severities": {
		"GUITKX0013": "error",
		"GUITKX0014": "error",
		"GUITKX0015": "error",
		"GUITKX0016": "error",
		"GUITKX0018": "warning",
		"GUITKX0019": "warning",
		"GUITKX0026": "error",
		"GUITKX0103": "warning",
		"GUITKX0104": "error",
		"GUITKX0105": "error",
		"GUITKX0106": "warning",
		"GUITKX0107": "hint",
		"GUITKX0108": "error",
		"GUITKX0109": "error",
		"GUITKX0111": "warning",
		"GUITKX0120": "error",
		"GUITKX0121": "error",
		"GUITKX0150": "warning",
		"GUITKX0300": "error",
		"GUITKX0301": "error",
		"GUITKX0302": "error",
		"GUITKX0303": "error",
		"GUITKX0304": "error",
		"GUITKX0305": "error",
		"GUITKX2100": "error",
		"GUITKX2101": "error",
		"GUITKX2102": "error",
		"GUITKX2103": "error",
		"GUITKX2104": "error",
		"GUITKX2105": "error",
		"GUITKX2106": "error",
		"GUITKX2107": "error",
		"GUITKX2203": "warning",
		"GUITKX2210": "error",
		"GUITKX2504": "error",
		"GUITKX2505": "error",
		"GUITKX2506": "error",
		"GUITKX2507": "error",
		"GUITKX2508": "error"
	},
	"v_factories": [
		"aspect",
		"audio",
		"button",
		"center",
		"check_box",
		"check_button",
		"code_edit",
		"color_picker",
		"color_picker_button",
		"color_rect",
		"comp",
		"control",
		"error_boundary",
		"fc",
		"flow_h",
		"flow_v",
		"foldable",
		"fragment",
		"grid",
		"h",
		"h_separator",
		"h_slider",
		"hbox",
		"item_list",
		"label",
		"line_edit",
		"link",
		"link_button",
		"margin",
		"memo",
		"menu_bar",
		"menu_button",
		"nav_link",
		"navigate",
		"nine_patch",
		"option_button",
		"outlet",
		"panel",
		"portal",
		"progress_bar",
		"rich_text",
		"route",
		"router",
		"routes",
		"scroll",
		"spin_box",
		"split_h",
		"split_v",
		"suspense",
		"tab_bar",
		"tabs",
		"text",
		"text_edit",
		"texture_button",
		"texture_progress",
		"texture_rect",
		"tree",
		"v_separator",
		"v_slider",
		"vbox",
		"video"
	]
}
